server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bc2504
    username: root
    password: admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379
    timeout: 6000